[phases.setup]
nixPkgs = ["nodejs", "chromium", "nss", "freetype", "freetype-woff", "harfbuzz", "ca-certificates", "ttf-freefont"]

[phases.build]
cmds = ["npm ci"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
